[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/blog/page/*"
  to = "/blog/page/[page].html"
  status = 200

[[redirects]]
  from = "/blog/category/*"
  to = "/blog/category/[category].html"
  status = 200

[[redirects]]
  from = "/blog/tag/*"
  to = "/blog/tag/[tag].html"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/[slug].html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404