[build]
  publish = "dist"
  command = "npm run build"

# Temporary countdown redirect - REMOVE AFTER JULY 11TH, 2025
[[redirects]]
  from = "/"
  to = "/countdown"
  status = 200
  force = true

[[redirects]]
  from = "/blog/page/*"
  to = "/blog?page=:splat"
  status = 200

[[redirects]]
  from = "/blog/category/*"
  to = "/blog/category/:splat"
  status = 200

[[redirects]]
  from = "/blog/tag/*"
  to = "/blog/tag/:splat"
  status = 200

[[redirects]]
  from = "/blog/*"
  to = "/blog/:splat"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404